services:
  db:
    image: postgres:16
    container_name: yrkesco-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wordpass
      POSTGRES_DB: yrkco_db
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data